language: c
dist: trusty
sudo: required
env:
  global:
  - BRIGHTAUTHOR_VERSION=0.99.0
os:
- osx
#- linux
node_js:
- '7'
cache:
  directories:
  - node_modules
install:
- nvm install 7.9.0
- npm install electron-builder@next
- npm install
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run publish-mac; fi
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run publish-linux; fi
deploy:
  - provider: script
    script: if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then echo $CERTIFICATE_OSX_APP_P12 | base64 --decode > CertApp.p12; echo $CERTIFICATE_OSX_INST_P12 | base64 --decode > CertInst.p12; export KEYCHAIN=build.keychain; security create-keychain -p $CERTIFICATE_OSX_PASSWORD $KEYCHAIN; security default-keychain -s $KEYCHAIN; security unlock-keychain -p $CERTIFICATE_OSX_PASSWORD $KEYCHAIN; security import $CERTIFICATE_OSX_APP_P12 -k $KEYCHAIN -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign; security import $CERTIFICATE_OSX_INST_P12 -k $KEYCHAIN -P $CERTIFICATE_OSX_PASSWORD -T /usr/bin/codesign; fi

  - provider: s3
    access_key_id: "$AWS_ACCESS_KEY_ID"
    secret_access_key: "$AWS_SECRET_ACCESS_KEY"
    bucket: brightauthor
    region: us-east-1
    skip_cleanup: true
    local_dir: release
    upload-dir: release/$BRIGHTAUTHOR_VERSION
    acl: public_read
notifications:
  slack:
    rooms:
      - brightsign:$SLACK_TOKEN#bsn-jenkins-sys
