language: c
dist: trusty
sudo: required
env:
  global:
  - BRIGHTAUTHOR_VERSION=0.11.1
  - secure: eohicJ6xUoskSMDmzHGgZ2qkHamLSf5sB5MXA6XMDTQvOgcLrPWu1L4BFwE0FE47IBVpIwVJ2II7HN7NHlyzNzLv7qhHnAClZQFoLRWhZF+Y3fv+U79JNtOWr54S6QKzFBI/bmjl9V5L7Su7WC4dyxxUMH5nO2zMHDhbiSGs1kemVJHlXcSRiXlMnnboQJcBxJCuleDz2OaNcOcsqn12qqI1zo1YHSvzasKQ3v9ZbeFvOiepdiVhHeDXGLNU5Fcjn1M6oWUtUi8SZ3H67SmiRcAXIdemnTKqlWucyxzu2n/xwC1K7ER5hmiq/QjlZRrtgHMimW8IyGsBb6DpprpHs016hAZTnXsttYgpu8uyrtyFlfNvfCHXryGn82G7FgTPgPv8AfMT0cwJO0xij79a0MpFb5VoDRsRDuGlZtEqC1SkBdWPgZKmctaWu2MPCyvn4OrhrUa8z2FOuNLlQ8fBUCml2Cu3by9nOuYtxgFINat6VBPtbp+F6obUIlEylfFGrOGbUOeTQyZk+NHuTm8t10UtfjHKAKPnySW/UAWgXn929b6GmBdrfRlgzFrOOuwoLw4QqpS0F+ykTkCSVJrYNCgQzR+65tKGcxQMpmy6quYPirlH+/yuB6Cq2RI1VTFIAY0xLyDIlz17hOhuBQUw1nOXHXU9CuTfP9xJnX/f29k=
  - secure: nOw1XUHENdf3ouLsEcnlZPt23cUS7vtrwCvfUm4e/ML0fCc8+UTjrSvIXxMW2XO2YuzBOh5wtJ8Lw1sFhi7APrNpwO8RFymn39VdWJu+p93o/ZfxOIhZDWAA/0wAzXzTSDMhZcN2KV6evjzkCb/9YG7vOBF/1VgCQrjYfw6RdINZKhr8GV33FTtHiIKmRE/Q4SqLPQJNDzP86dp9kAUuj7E+GeJY2XT+bh57vFg8V3zVKJSx2vXEJnRf+D0Drwjfit6DZC5u0qm5G6DBKkrnc3Ju4oHJkM4i8a46Pu90/JMPyto4HnaJwbbStBQen5OJDrAgmKqiMnL3tphqtSu0FBs8Kz+cxJHQAbiTmymeQL6iZgN7obJyUu26QEczbxIDI7FsPSDTB+sUrVX9WW6fxC6V2ZnXxgFcISfgwBOrSb9h95Xc3rB9xwzG4A8S5E5dEhN62xzs89AUfPQ+ey4vZ8sYcFLsq3OqjNcPK2jmFqnSZGUzzQXtnBESjDgh8UlB1UB9Zz/RENcv1JM0zx8PWsBGNX1eIlyQjgJSosH/adO/VSdRMDWQ2ngAcHHEvbMwoVu+tHiqkvg+3uGbCv+/oAVhIRsKIY+dip8NVqUYGzeXmgz/eYiDMPP+ruoc2J2EiFhuzgvd2IkLArgBYOEMajzQprAjKbp2h7nXIPJRs80=
  - secure: ScNbyUqL7oi7CQ6wMp3OyN3lIs+Hp7SsjByhlf+yK2hSmZKJTRrmGKr12H5/7243KMAkZapRqcda5Hnvq5Y1I6nQL1vdrzSf6xaySQfgzd3UbQZlQuRdEBWViuHxNV0cUrnvVWpjLRhE94zb/PealXCaef9IgYqR6XoEc6FyFSvlL8ZUY33l9a1d6jNrcGBnlbWPeUT2OfHr+UbSBBtR7P7pFZRajXP7uoxhO+W8/Q9/GdoaAzTXlSUX9A+/64buwCHYoqGGqgqVYYLVtmXJ+I0MbYH3G2jO6Ke+YiTyujgvyLuiSHHtH8Ly8iF7/mX1gC/ynSDC4OQcWwhFV3snEa2zlRtTSYjpgpIMm21wJPwHiClFU3mcwk3VCSbEFZcJZ9NoKKSINmCrGqDpL+vBCE4+3IAjThTCt3Pv8Ekewlrd0qqUtuOnaDpWATe7ZwRt5IBuKLx/lufdi6JadgNFeoFriEUV9nAZPhbtgPQv0s9JyRFwP1FThJoetXLiEpG3Uimn1mkFnBLwglJ59BKc3B3lRRI5EfBSIGB2R5f7D2YqrqtrL6/IL22OIFfRwcolFyoemM4oVfkNpdV/b6C2E1Zwrv6iI3QXMw/JSsoSSePuOORO4lgLOjvIerXlmS5w12pK4sAhBQodCv5QVQTq5v6JRfACrd1CgLo4RNLqrO8=
os:
- osx
- linux
node_js:
- '7'
cache:
  directories:
  - node_modules
install:
- nvm install 7.9.0
- npm install electron-builder@next
- npm install
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run publish-mac; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run publish-linux; fi
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: brightauthor
  region: us-east-1
  skip_cleanup: true
  local_dir: release
  upload-dir: release/$BRIGHTAUTHOR_VERSION
  acl: public_read
notifications:
  slack:
    rooms:
      secure: ey+dLyfkv2fiIothrvfKG9VXWK0xvZaySRab/dxc3ZPls7y8t0+IhwIrvIv3Q75ITm5WvPftr8FENfEUKF+kSBjfwU821Q6wYeQ3bFlcZTJsEQueMagGPmPbaE3nR4h7YCg0ZjbRI+UCvj7RV3w3bj3/m4kykq2Up5SoDv1VT+CdMoGVCtA/fKbvc7mqoplmlr4qI2TDaex7hibhNSZ9Wa4woFBXwBQl/5ONGxzx7+dKGruqPn53QERR8sMQ5npKcKg62gwdslRGY6guDfrhb4MfrgnjQ0RXs35UUSgD8+5d8/cA/qLbKanjElVOJaid6LLdV0arEqgM3Zmhj2NlkxpksDllgMUxcl+u+Q8YIb7N7Sgf1cPsLt9uOqIZ0DDXMDggLHfCpyOCn8T3f7Mm8uSBEVfBdqa9n7mh1wJw+HDDSG4rIfTGfCmpkhAegvBey0nQUnAz13wwCt6Y/7DHV9q2earT/BBCfKIWEkSew7xfqU1sZJc5JIhTpNkZubtkzdvfqv4CP3EBObfx7lU8LVlyAuj3aXwnFf65vtKK76Q4pVJb9YS8LDD/+92vfXil5hSB/miJcMMcserALbNecrPjY1d7j+RFZPb7n+Eki/15oyuIzx+j983wjV3Z0hjBLkkFljefm17z756Eb2XuVphZTF0dgI6s948jp5ayDuU=
