language: c
dist: trusty
sudo: required
env:
  global:
  - BRIGHTAUTHOR_VERSION=0.10.0
  - secure: eohicJ6xUoskSMDmzHGgZ2qkHamLSf5sB5MXA6XMDTQvOgcLrPWu1L4BFwE0FE47IBVpIwVJ2II7HN7NHlyzNzLv7qhHnAClZQFoLRWhZF+Y3fv+U79JNtOWr54S6QKzFBI/bmjl9V5L7Su7WC4dyxxUMH5nO2zMHDhbiSGs1kemVJHlXcSRiXlMnnboQJcBxJCuleDz2OaNcOcsqn12qqI1zo1YHSvzasKQ3v9ZbeFvOiepdiVhHeDXGLNU5Fcjn1M6oWUtUi8SZ3H67SmiRcAXIdemnTKqlWucyxzu2n/xwC1K7ER5hmiq/QjlZRrtgHMimW8IyGsBb6DpprpHs016hAZTnXsttYgpu8uyrtyFlfNvfCHXryGn82G7FgTPgPv8AfMT0cwJO0xij79a0MpFb5VoDRsRDuGlZtEqC1SkBdWPgZKmctaWu2MPCyvn4OrhrUa8z2FOuNLlQ8fBUCml2Cu3by9nOuYtxgFINat6VBPtbp+F6obUIlEylfFGrOGbUOeTQyZk+NHuTm8t10UtfjHKAKPnySW/UAWgXn929b6GmBdrfRlgzFrOOuwoLw4QqpS0F+ykTkCSVJrYNCgQzR+65tKGcxQMpmy6quYPirlH+/yuB6Cq2RI1VTFIAY0xLyDIlz17hOhuBQUw1nOXHXU9CuTfP9xJnX/f29k=
  - secure: nOw1XUHENdf3ouLsEcnlZPt23cUS7vtrwCvfUm4e/ML0fCc8+UTjrSvIXxMW2XO2YuzBOh5wtJ8Lw1sFhi7APrNpwO8RFymn39VdWJu+p93o/ZfxOIhZDWAA/0wAzXzTSDMhZcN2KV6evjzkCb/9YG7vOBF/1VgCQrjYfw6RdINZKhr8GV33FTtHiIKmRE/Q4SqLPQJNDzP86dp9kAUuj7E+GeJY2XT+bh57vFg8V3zVKJSx2vXEJnRf+D0Drwjfit6DZC5u0qm5G6DBKkrnc3Ju4oHJkM4i8a46Pu90/JMPyto4HnaJwbbStBQen5OJDrAgmKqiMnL3tphqtSu0FBs8Kz+cxJHQAbiTmymeQL6iZgN7obJyUu26QEczbxIDI7FsPSDTB+sUrVX9WW6fxC6V2ZnXxgFcISfgwBOrSb9h95Xc3rB9xwzG4A8S5E5dEhN62xzs89AUfPQ+ey4vZ8sYcFLsq3OqjNcPK2jmFqnSZGUzzQXtnBESjDgh8UlB1UB9Zz/RENcv1JM0zx8PWsBGNX1eIlyQjgJSosH/adO/VSdRMDWQ2ngAcHHEvbMwoVu+tHiqkvg+3uGbCv+/oAVhIRsKIY+dip8NVqUYGzeXmgz/eYiDMPP+ruoc2J2EiFhuzgvd2IkLArgBYOEMajzQprAjKbp2h7nXIPJRs80=
os:
- osx
- linux
node_js:
- '7'
cache:
  directories:
  - node_modules
install:
- nvm install 7.9.0
- npm install electron-builder@next
- npm install
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run package-mac; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run package-linux; fi
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: brightauthor
  region: us-east-1
  skip_cleanup: true
  local_dir: release
  upload-dir: release/$BRIGHTAUTHOR_VERSION
  acl: public_read
notifications:
  slack:
    rooms:
      secure: P+H6Zj7kkky72KGz9W/VvE/BQTxUjcWcfHLgJ1zsCgflYqq/T4ncHJNJnzwpCXYAVnKF/313yAIpzh8qW6wb1//5aSgGIb0KP8mMOGuAzCnP3kH7+aR4JSWsMnvVtgz4d8AJeigR2I+Gkp4paxwoiqflt7VITpMThsquLSlIi0Zwnwvb7wzkDraDN0Pk9DcbCAuhC0o3+vdcp6oaa22oLRvV+d44YbEAImr4trhYuxZ8widWKBPBZxFh291l8K3EV0ee0AFOPBbAEtRIesddIDfk9pzO1Tl5nC2+xetF8attnCYeTQQ9wOLiyIW755HgBQqK/JMQAvtHT943w1dsJ7Xyubl5Y2mWAx15kD+dWWegiXST6q4GIdGm0/DVMVKamkWOooial6IIIAubO0CzzL8hwQDS+8EqJJ5WQ23vWbwwx9oHRHKzK64+I3njZrjpHlK6J9nlhQaGB51GXe3eRZ09G8cEKtIkl1s58vu8oN4gYKOXdWNLm6V8+sX3ov22kZEfaoApXB/vSPWRn7HmdBvtr/SUAg6gpcW6njqrzRsZP8VQFtYk2vvZQd21jwWVGHwNmL9EWDKCKCxNsVLIO+WJP1fs9pdxbaF/I6WSZ1hOiRbQLoQHODqIB92RQ89l/+W5mvDPHiDJKP9jrSk+cVvgDQXtzCwSxpXtjPczZB8=
