dist: trusty
sudo: required
env:
  global:
  - BRIGHTAUTHOR_VERSION=0.99.0
env:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
matrix:
  include:
  - os: osx
    language: node_js
    osx_image: xcode9.0
  - os: linux
    language: generic
node_js:
- '7'
cache:
  directories:
    - node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
install:
- nvm install 7.9.0
- npm install electron-builder@next
- npm install
script:
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then npm run publish-mac; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then npm run publish-linux; fi
deploy:
  provider: s3
  access_key_id: "$AWS_ACCESS_KEY_ID"
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
  bucket: brightauthor
  region: us-east-1
  skip_cleanup: true
  local_dir: release
  upload-dir: release/$BRIGHTAUTHOR_VERSION
  acl: public_read
notifications:
  slack:
    rooms:
      - brightsign:$SLACK_TOKEN#bsn-jenkins-sys
